### ISSUE TITLE
Document steps to run benchmark

### ISSUE THREAD

**Issue by johnymontana** [tsegismont/graphql-server-benchmark#3]
This looks really neat and I'm interested in adding an implementation, however, I can't seem to figure out how to run the benchmarks against the current implementations.

It would be great to have the steps / scripts needed to run the benchmarks included the readme. Thanks!

**Comment by tsegismont** [comment]
To run the benchmarks:

- clone the project on your injector machine
- execute the `run-benchmarks.sh` script in the project directory, providing the relative path to the framework tested

Here's an example

```
git clone https://github.com/tsegismont/graphql-server-benchmark.git
cd graphql-server-benchmark
./run-benchmarks.sh Java/vertx-graphql-java
```

By default, the benchmark tries to connect to `localhost`. To configure the host part, export a `SERVER_HOST` variable before starting.

**Comment by tsegismont** [comment]
@johnymontana the steps above are off the top of my head. After trying, would you mind to update the README? Thank you

**Comment by johnymontana** [comment]
@tsegismont Thanks for the quick response. When I try running the `run-benchmarks.sh` script I get the following error:

```
./run-benchmarks.sh Java/vertx-graphql-java
Warming up framework Java/vertx-graphql-java for benchmark all-posts-desktop.lua...
unable to connect to localhost:8080 Connection refused
```

I've installed `wrk` and `lua`, not sure if there are other necessary dependencies? Any suggestions how to debug?

**Comment by tsegismont** [comment]
@johnymontana This means no server is listening. Have you started your local server for testing?
